name: "demo"
on:
- push

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Remove broken apt repos [Ubuntu]
      if: matrix.os == 'ubuntu-latest'
      run: |
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
    - name: Download deps
      run: |
        cp vcd2wavedrom/vcd2wavedrom.py docs/
        pip download -r requirements.txt
        cp src/vcdvcd/vcdvcd/vcdvcd.py docs/
    - name: Commit changes
      run: |
        git clone https://github.com/nobodywasishere/vcd2wavedrom.git --branch gh-pages --single-branch gh-pages
        cd gh-pages
        git rm -rf .
        git clean -fxd
        cp -r ../docs/* .
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}